Якупов 2.1.9
k0c0w/dotnet-homeworks-2 pull request #13
Opened 2022-11-05 16:26 UTC by k0c0w

2022-11-09 17:48 UTC, TimurSadorov commented on Homework9/Hw9.DesktopClient/CalculatorForm.cs
> +            new KeyValuePair<string, string>("", textBox.Text)
почему тут название параметра на написано?

2022-11-09 17:48 UTC, TimurSadorov commented on Homework9/Hw9.DesktopClient/CalculatorForm.cs
> +            var response = await client.PostAsync(@"https://localhost:7190/Calculator/CalculateMathExpression", content);
Есть метод PostAsJsonAsync

2022-11-09 17:48 UTC, TimurSadorov commented on Homework9/Hw9.DesktopClient/CalculatorForm.cs
> +                answer = responseText.Substring(res + 8, responseText.Length - res - 9);
И вот это уже все не нужно будет

2022-11-09 17:48 UTC, TimurSadorov commented on Homework9/Hw9.DesktopClient/CalculatorForm.cs
> +        await Task.Yield();
Для чего это ?

2022-11-09 17:48 UTC, TimurSadorov commented on Homework9/Hw9.DesktopClient/CalculatorForm.cs
> +            answer = "���-�� ����� �� ���...";
У тебя какая кодировка стоит ? У меня такая хрень в answer: ���-�� ����� �� ���...

2022-11-09 17:48 UTC, TimurSadorov commented on Homework9/Hw9.Tests/MyMethodsTests.cs
> +public class MyMethodsTests
В случаи модульных тестов, нейминг обычно такой "{Название тестируемого класса}Tests"

2022-11-09 17:48 UTC, TimurSadorov commented on Homework9/Hw9.Tests/MyMethodsTests.cs
> +    public async Task ThrowsExceptionOnUnsupportedTypes()
Про нейминг методов в тестах вам аршик должен был в начале года вроде кинуть. Обычно методы именуются примерно так "{Название тестируемого метода}_{Входное значение}_{Ожидаемое поведение}". Это один из вариантов, моешь в инете почекать

2022-11-09 17:48 UTC, TimurSadorov commented on Homework9/Hw9.Tests/MyMethodsTests.cs
> +    public async Task ThrowsOnUnsupportedExpressionTypes()
По-моему здесь просто void, может ошибаюсь конечно и тесты не будут работать

2022-11-09 17:53 UTC, k0c0w commented on Homework9/Hw9.DesktopClient/CalculatorForm.cs
> +        await Task.Yield();
а чета Post не работает без этого, там какая то проверка не дает ответ

2022-11-09 17:58 UTC, k0c0w commented on Homework9/Hw9.DesktopClient/CalculatorForm.cs
> +            answer = "���-�� ����� �� ���...";
UTF-8 вроде как

2022-11-16 15:30 UTC, TimurSadorov requested changes

2022-11-16 15:30 UTC, TimurSadorov commented on Homework9/Hw9/Services/MathCalculator/ExpressionWorkers/ExpressionCalculator.cs
> +                if (Expression.Lambda(exp).Compile() is Func<double> resultFunc)
Компайл долго работает, тем более есть ExpressionConstant, если ты на число хочешь проверить, то используй его

2022-11-20 10:19 UTC, k0c0w commented on Homework9/Hw9/Services/MathCalculator/ExpressionWorkers/MathExpressionParser.cs
> +        var operationStack = new Stack<OneOf<char, MathOperation>>();
стек нужен для поддержания корректной очереди операций с учетом скобок, в нем лежат как операции, так и скобки. Я подумал, что вместо кастов к object будет лучше использовать OneOf

2022-11-20 11:36 UTC, k0c0w commented on Homework9/Hw9/Services/MathCalculator/ExpressionWorkers/ExpressionCalculator.cs
> +                    await Task.Yield();
Если не сделать Yield(), код может выполниться в один поток. Yield возвращает, что таск не выполнен и продолжение вызывается не на том же потоке

2022-11-20 13:11 UTC, k0c0w commented
Короче  я не могу никак протестировать эту строчку

2022-11-20 13:13 UTC, k0c0w commented on Homework9/Hw9/Services/MathCalculator/ExpressionWorkers/ExpressionCalculator.cs
> +                throw new InvalidOperationException($"Unsupported expression {exp}!");
Короче я не могу протестировать эту строчку никак

2022-11-20 14:22 UTC, TimurSadorov requested changes

2022-11-20 14:22 UTC, TimurSadorov commented on Homework9/Hw9/Services/MathCalculator/MathCalculatorService.cs
> +    public MathCalculatorService([FromServices] IAsyncMathExpressionCalculator compiler,
FromServices не нужно писать, он сам поймет что из di надо достать

2022-11-20 14:22 UTC, TimurSadorov commented on Homework9/Hw9/Services/MathCalculator/ExpressionWorkers/ExpressionCalculator.cs
> +                    await Task.Yield();
А в чем проблема, если в один поток выполнится?

2022-11-20 14:22 UTC, TimurSadorov commented on Homework9/Hw9/Services/MathCalculator/ExpressionWorkers/ExpressionCalculator.cs
> +                    await Task.Yield();
И тем более он не выполниться в один поток вроде как все равно

2022-11-20 14:25 UTC, TimurSadorov commented on Homework9/Hw9/Services/MathCalculator/ExpressionWorkers/ExpressionCalculator.cs
> +                throw new InvalidOperationException($"Unsupported expression {exp}!");
На это забей тогда

2022-11-20 14:25 UTC, k0c0w commented on Homework9/Hw9/Services/MathCalculator/ExpressionWorkers/ExpressionCalculator.cs
> +                    await Task.Yield();
а смысл тогда параллелить?

2022-11-20 14:29 UTC, TimurSadorov requested changes

2022-11-20 14:29 UTC, TimurSadorov commented on Homework9/Hw9/Services/MathCalculator/ExpressionWorkers/MathExpressionTraverser.cs
> +    private new Expression? Visit(Expression? node)
А почему new и приватный ?

2022-11-20 14:33 UTC, k0c0w commented on Homework9/Hw9/Services/MathCalculator/ExpressionWorkers/MathExpressionTraverser.cs
> +    private new Expression? Visit(Expression? node)
чтобы скрыть Visit, чтобы извне использовать только метод интерфейса

2022-11-20 14:48 UTC, merged